print('')
print('Hi!👋 this is the square area calculator \n')
h = float(input('1️⃣ Please insert the square height: '))
w = float(input('2️⃣ Please insert the square width: '))
area = round((h * w), 2)
perimeter = (h + w) * 2
print('')
print(f'🟩 The square area is {area}')
print(f'⏹️ The square perimeter is {perimeter}')
print('')
print('Thanks for use this app! 👌')
